apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{  include "hello-kubernetes.name" . }}
  namespace: hello-kubernetes
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  rules:
  - host: dolfo.balto
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{  include "hello-kubernetes.name" . }}
            port:
              number: {{ .Values.service.port }}