apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-kubernetes.name" . }}
  namespace: hello-kubernetes
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "hello-kubernetes.selectorLabels" . | nindent 4 }}
